### ISSUE TITLE
asyncio.wait_for

### ISSUE THREAD

**Issue by yunstanford** [aio-libs/async-timeout#10]
Is there any reason of not using `asyncio wait_for` https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for ? 

What's the motivation of this lib ? any pro ?

**Comment by hellysmile** [comment]
First of all it is usefull context manager, as well async-timeout is a bit faster, cuz do not create extra task.

**Comment by asvetlov** [comment]
Just compare
```
async def inner():
    await asyncio.sleep(1)

async def outer():
    await asyncio.wait_for(inner(), 0.5)
```
with
```
async def outer():
   async with timeout(0.5):
       await sleep(1)
```

Do you have any problem with this context manager?

**Comment by yunstanford** [comment]
ok, thanks guys. it works fine. I just curious if there's any other pro. 

Thanks.
