### ISSUE TITLE
Missing typing_extensions package

### ISSUE THREAD

**Issue by ross-weir** [aio-libs/async-timeout#121]
I'm using a package that has `async-timeout` as a dependency, recently I have started getting an error about a missing package in `async-timout`:

```
  ...
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 8, in <module>
    from typing_extensions import final
ModuleNotFoundError: No module named 'typing_extensions'
```

Wanted to make you aware. Thanks! :-)

**Comment by asvetlov** [comment]
Fixed. Thanks!
Do you use an unreleased master branch for testing only or not?
