### ISSUE TITLE
Please tag a new stable release

### ISSUE THREAD

**Issue by polyzen** [aio-libs/async-timeout#143]
Seems your current alpha is in a stable state, since tests keep passing on [dependency updates](https://github.com/aio-libs/async-timeout/compare/v4.0.0a2...master). We would like to get aiohttp to cut a new release for us to package, as its tests for 3.6.2 result in many failures due to syntax changes in Python 3.8. aiohttp trunk currently requires `'async_timeout>=4.0a2,<5.0'`, and it would be great if you could tag a new stable release for downstream to use.

**Comment by trendelkampschroer** [comment]
+1. The whole conda packaging approach "breaks down" (becomes very, very hard to maintain) if pre-releases become "stable" dependencies.

**Comment by asvetlov** [comment]
There is no published library that uses async-timeout 4.x
The latest published aiohttp works with 3.x; it has "async_timeout>=3.0,<4.0" in the library requirements.

Technically I can publish new async-timeout release but it is not compatible with the latest aiohttp 3.x line.
Where do you want to use it?

**Comment by sbraz** [comment]
The tests from 3.0.1 fail with Python 3.10, are there any plans to release a new version with passing tests or should we backports fixes from git?

**Comment by asvetlov** [comment]
async-timeout 4.0 released
