### ISSUE TITLE
The way to prevent raise asyncio.TimeoutError

### ISSUE THREAD

**Issue by stavinsky** [aio-libs/async-timeout#26]
Hello. Sorry for maybe stupid question. 
Can I do something to prevent timeout error, except using ```try``` outside CM?
If no, maybe it is good idea to use some flag, for example ```silent=True``` to make such behavior possible?

**Comment by asvetlov** [comment]
Use https://docs.python.org/3/library/contextlib.html#contextlib.suppress

**Comment by stavinsky** [comment]
Thanks. I didn't know about such thing.
