### ISSUE TITLE
a bug or ?

### ISSUE THREAD

**Issue by viponedream** [aio-libs/async-timeout#260]
i set 1000 seconds 
but only the first time it runs well 
next  round only 10 seconds , it says timeout
what's wrong with my code?

    async def _run_debug_mode(self):
        for idx, wallet in enumerate(self.wallets):
            await self._run_timeout(wallet=wallet, delay=(idx + 1)*self.timeout_each_account)
            await self.end_session()

    async def _run_timeout(self, wallet=None, delay=None):
        begin_time = datetime.datetime.now()
        try:
            async with async_timeout.timeout(delay) as cm:
                await self._run_one(wallet)
        except:
            await self.end_session()
            end_time = datetime.datetime.now()
            msg = f'运行超时: {wallet.wallet} || 耗时: {end_time-begin_time}'
            self.write_log(msg)

**Comment by asvetlov** [comment]
Your code is not full.
Sorry, I cannot run it and check does it work as expected or not.
