### ISSUE TITLE
There is no way to set `timeout=0` for immediate cancelation

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/async-timeout#27]
`timeout=0` will be set to `None` due https://github.com/aio-libs/async-timeout/blob/master/async_timeout/__init__.py#L22

`timeout=0` or any special flag for instant timeout can be useful 

As well it makes different behaviour with `asyncio.wait_for`, cuz it supports `timeout=0`

https://github.com/aio-libs/async-timeout/blob/master/async_timeout/__init__.py#L22

what about implementing `timeout=async_timeout.immediate` ? If it makes sense I'll do PR

**Comment by asvetlov** [comment]
We could distinguish `None` from `0`.

**Comment by hellysmile** [comment]
It will huge backword incopability

**Comment by hellysmile** [comment]
I think it makes sense to copy behaviour `asyncio.wait_for`, as well there is a patch for asyncio itself
https://github.com/python/cpython/pull/3703 which changes little bit `timeout=0`. Ill do pr when `asyncio.wait_for` changes will be accepted or declined

**Comment by hellysmile** [comment]
Closed by https://github.com/aio-libs/async-timeout/pull/28
