### ISSUE TITLE
Add `msg` to `task.cancel()` method to allow distinguish the source of cancellation

### ISSUE THREAD

**Issue by achimnol** [aio-libs/async-timeout#320]
How about adding `msg` argument to `task.cancel()`?

TL;DR:
```python
def _on_timeout(self, task: "asyncio.Task[None]") -> None:
    task.cancel(msg="timeout")  # <--- add the reason of cancellation
    self._state = _State.TIMEOUT
    # drop the reference early
    self._timeout_handler = None
```

This would be useful to distinguish the reason of cancellation in library's user programs.

**Comment by ljluestc** [comment]
import asyncio

class CustomTask(asyncio.Task):
    def cancel(self, msg=None):
        self._msg = msg
        super().cancel()

def _on_timeout(self, task: "asyncio.Task[None]") -> None:
    task.cancel(msg="timeout")  # Adding a custom reason for cancellation
    self._state = _State.TIMEOUT
    # Drop the reference early
    self._timeout_handler = None

# Replace asyncio.Task with CustomTask wherever you want to use it
async def main():
    loop = asyncio.get_event_loop()
    task = loop.create_task(async_func())
    await asyncio.sleep(1)
    task.cancel("custom_reason")

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()

**Comment by asvetlov** [comment]
Version 5.0+ works exactly as `asyncio` built-in does, nothing to do here.
