### ISSUE TITLE
Version 3.0.0 fails on python 3.5.1

### ISSUE THREAD

**Issue by xobb1t** [aio-libs/async-timeout#38]
Hi!

It was added some type hints in version 3.0.0. But in python 3.5.1 `typing.Type` is not available.

```
from typing import Optional, Type
ImportError: cannot import name 'Type'
```

**Comment by asvetlov** [comment]
Surely yes.
Old versions have been dropped, the minimally supported python is 3.5.3: https://github.com/aio-libs/async-timeout/blob/master/setup.py#L43
How did you install a fresh asyncio-timeout on old Python? `pip` should forbid it.
