### ISSUE TITLE
Ner version release

### ISSUE THREAD

**Issue by StuntsPT** [aio-libs/async-timeout#4]
The latest commits to the repository mention a new release (1.1.1), but there isn't a new release on github.
Was this intentional?
Thanks!

**Comment by fafhrd91** [comment]
Do you have any specific reasons to try latest code?

**Comment by fafhrd91** [comment]
released

**Comment by StuntsPT** [comment]
Hi @fafhrd91 
I am the maintainer for the Archlinux [AUR package](https://aur.archlinux.org/packages/python-async-timeout/), thus I "follow" the changes to the repository to package a new release ASAP.
I just found it odd that the release notes mentioned a new version but there was no release (I prefer not to use the `master` branch, but rather a stable release to repackage).
Anyway, thank you for making a new release. It really simplifies packaging, rather than using a git snapshot.

**Comment by fafhrd91** [comment]
oh, ok.

thanks
