### ISSUE TITLE
Python 3.5.3 requirement

### ISSUE THREAD

**Issue by apollo13** [aio-libs/async-timeout#40]
Is there a hard requirement for Python 3.5.3? I am asking because ubuntu xenial ships with python 3.5.1 and therefore cannot install this package. If possible, could we change the requirement to python 3.5 instead?

Also note that distrbutions partially have large backports, so 3.5.1 is probably something like 3.5.1 with a pile of patches and probably similar enough to 3.5.3

**Comment by asvetlov** [comment]
Sorry, yes. 3.5.3 has some crucial updates.

Please consider using old asyncio-timeout if you cannot upgrade your distribution to the latest Ubuntu Bionic LTS.

**Comment by apollo13** [comment]
I couldn't find anything crucial in the release notes for python 3.5.2/3 -- can you point me to those curcial changes? We will have to evaluate if an older asyncio-timeout works for us, or if we need to upgrade python or find another workaround.

Upgrading to Ubuntu Bionic is sadly not an option since it is (at least currently) **not** really an LTS release. The ubuntu update manager itself will only show it as update once 18.04.1 is released, so canonical itself does not yet consider it fit for LTS usage.

**Comment by asvetlov** [comment]
1. `get_event_loop()` fixed
2. aiohttp, the main library upstream, upgraded to 3.5.3

Perhaps none of them is important for you, so you can stay with 2.0 until Canonical will publish a new LTS

**Comment by apollo13** [comment]
Thank you!

**Comment by agronholm** [comment]
@apollo13 Consider switching to Docker so you won't need to rely on whatever version of Python your OS vendor chooses to provide. We did and never looked back.
