### ISSUE TITLE
Drop support for Python 3.8 (and older)?

### ISSUE THREAD

**Issue by Hedda** [aio-libs/async-timeout#413]
Python 3.8 is currently receiving only security updates and that will end next month, so maybe to drop support for Python 3.8?

That it, should now require at least Python 3.9 or later?

But note that even Python 3.9 is EoL (End-of-Life) now and will stop receiving all updates (including security) next year so you ideally would want to be on at least Python 3.10 or preferably Python 3.11

Regardless, it would be best to push your to the highest version of Python possible.

**Comment by Dreamsorcerer** [comment]
For anybody looking for this response: https://github.com/aio-libs/async-timeout/pull/372#issuecomment-2326450246

**Comment by asvetlov** [comment]
Python 3.8 is still supported because it costs nothing.
Starting from async_timeout 5.0+ the library works exactly as `asyncio` built-in does on Python 3.11+.
