### ISSUE TITLE
sdist is missing `requirements.txt`

### ISSUE THREAD

**Issue by mtelka** [aio-libs/async-timeout#423]
The sdist package at PyPI is missing the [requirements.txt](https://github.com/aio-libs/async-timeout/blob/master/requirements.txt) file with the list of testing dependencies.  Please add the missing file to sdist to make downstream testing easier.  Thank you.

**Comment by asvetlov** [comment]
Thanks for the report!

#425 should fix it.

**Comment by asvetlov** [comment]
Fixed by async-timeout 5.0.1
