### ISSUE TITLE
nesting

### ISSUE THREAD

**Issue by kshpytsya** [aio-libs/async-timeout#50]
This is more of a question than a bug report.

Is nesting of `timeout` context managers supported? If it is, I would expect to find a test case (maybe I have missed it). In any case, it would be nice for this to be explicitly documented.

**Comment by asvetlov** [comment]
1. The library supports nested context managers
2. The feature is not documented because I didn't consider the nesting as something special.
3. If you want to improve docs -- please make a Pull Request.

**Comment by kshpytsya** [comment]
How about adding an explicit test case?

**Comment by asvetlov** [comment]
If you want to make a test -- I'll review it with pleasure.

**Comment by asvetlov** [comment]
Closing as inactive
