### ISSUE TITLE
Usage without context (as wait_for)

### ISSUE THREAD

**Issue by wWolfovich** [aio-libs/async-timeout#87]
Is it possible to add support for calling timeout() with waitable as argument without creating context, or will it decrease performance?
I have a case where I use asyncio.wait_for for limiting only connection time of asyncssh.connect which itself creates connection context, but I don't want to limit commands execution time.

**Comment by wWolfovich** [comment]
I also experience a strange behavior of wait_for, or I don't understand how it works.
I get different results depending on number of simultaneous tasks. It is more than enough 1 sec. to connect with asyncssh in my environment if host is up, but when I set  >100 simultaneous tasks at the same time, it cancels most tasks, so I have to increase timeout value significantly.

So I wanted to try your implementation.

**Comment by asvetlov** [comment]
Sorry for the late reply.
I don't think that `async_timeout` should support non-contextmanager form: `wait_for()` already exists for connection.
